name: Test Maxwell problem solver

on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"
env:
  PETSC_DIR: /tmp/petsc
  PETSC_ARCH: linux-gnu-real-32
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on:
      ubuntu-latest
    container: fenicsproject/test-env:nightly-mpich

    steps:
      - uses: actions/checkout@v3

   
      - name: Get Basix
        uses: actions/checkout@v3
        with:
          path: ./basix
          repository: FEniCS/basix
          ref: main

      - name: Install UFL, Basix, FFCx
        run: |
          cmake -G Ninja -B build-basix -DCMAKE_BUILD_TYPE="Release" -S ./basix/cpp/
          cmake --build build-basix --parallel 3
          cmake --install build-basix
          BUILD_TYPE="Release" pip3 install ./basix/python
          python3 -m pip install git+https://github.com/FEniCS/ufl.git
          python3 -m pip install git+https://github.com/FEniCS/ffcx.git

      - name: Get DOLFINx
        uses: actions/checkout@v3
        with:
          path: ./dolfinx
          repository: FEniCS/dolfinx
          ref: dokken/discrete_interpolation_matrix

      - name: Configure C++ (dolfinx)
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE="Debug" -B build-dolfinx -S ./dolfinx/cpp/

      - name: Build and install C++ library (dolfinx)
        run: |
          cmake --build build-dolfinx
          cmake --install build-dolfinx

      - name: Build Python interface (dolfinx)
        run: BUILD_TYPE="Debug" python3 -m pip -v install ./dolfinx/python/

      - name: Flake8 code
        run: flake8 *.py

      - name: Install dependencies
        run: |
          pip3 install tqdm
    
      - name: Run test
        run: |
          python3 problems.py
          python3 convergence.py
          python3 iterations.py

      - name: Run test (higher order)
        run: |
          python3 problems.py --k =2
 